name: mtudor130@gmail.com
on:/Instagram 
  workflow_dispatch
jobs:no
  build: [iCloud iPhone 6]
    runs-on: ubuntu-latest
    steps:#646
      - uses: actions /checkout@master parolă/
      - name: Pause for 25 seconds
        run: |iPhone 6s
          echo $INPUT_FOO
          sleep 25
